live: false
live_url: 'http://82.161.93.185:5678/lorikeet.ogg'
mixcloud_url: 'https://www.mixcloud.com/RedLightRadio/lorikeets-pakistani-treasure-chest-ii-red-light-radio-05-22-2019/'
paginate: 3
paginate_path: '/posts/page:num/'
future: true
plugins:
  - jekyll-redirect-from

collections:
  trade_items:
    output: true
  categories:
    output: true
