live: false
live_url: 'http://178.84.201.59:40504/lorikeet.ogg'
mixcloud_url: 'https://www.mixcloud.com/RedLightRadio/eindbaas-lori-keet-red-light-radio-11-09-2017/'
paginate: 3
paginate_path: '/posts/page:num/'
