live: false
live_url: 'http://178.84.201.59:40504/lorikeet.ogg'
mixcloud_url: 'https://www.mixcloud.com/operator_radio/eindbaas-en-lorikeet-20th-january-2018/'
paginate: 3
paginate_path: '/posts/page:num/'
future: true
