live:
  on_air: false
  url: 'http://82.161.93.185:5678/lorikeet.ogg'
mixcloud_url: 'https://www.mixcloud.com/lorikeet/lorikeet-radio-episode-ii-20190727/'
paginate: 3
paginate_path: '/posts/page:num/'
future: true
plugins:
  - jekyll-redirect-from

collections:
  trade_items:
    output: true
  categories:
    output: true
