live: true
live_url: 'http://82.161.93.185:5678/lorikeet.ogg'
mixcloud_url: 'https://www.mixcloud.com/lorikeet/candela/'
paginate: 3
paginate_path: '/posts/page:num/'
future: true
plugins:
  - jekyll-redirect-from
